- set_fact:
    php_packages:
      - php-fpm
      - php-curl
      - php-gd
      - php-gmp
      - php-json
      - php-ldap
      - php-xmlrpc
      - php-xsl
      - php-imap
      - php-intl
      - php-mcrypt
      - php-mysqlnd

- name: php | install
  yum: 
    name: "{{ item }}"
  with_items: "{{ php_packages }}"
  when: ansible_pkg_mgr == "yum" 
